global:
  scrape_interval: 5s  # Lấy dữ liệu mỗi 5 giây

scrape_configs:
  - job_name: 'app-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9090']  # Kết nối từ Docker Prometheus đến ứng dụng chạy local
