
server:
  port: 9095
app:
  api-prefix: /api/v1
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: http://localhost:9090
          predicates:
            - Path=${app.api-prefix}/core/**
          filters:
            StripPrefix= 2