server:
  port: 8081

spring:
  application:
  name:
    keycloak
  datasource:
    url: jdbc:mysql://localhost:3307/core_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 11111
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: admin-cli
            client-secret: idypcFNNZgXHJsr62XyMQpho9BN4GVA6
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/SpringAPI